command: ['chainlit', 'run', 'app.py']


env: 
  - name: CHAINLIT_AUTH_SECRET
    value: "F8*9Z/LVfsoHzEt_/IvaI4s1-.1cd/bQ%Bmd5w5$FcXP$ga=taQR_,YE9Q91xnSG"

  - name: DATABASE_INSTANCE
    value: "lakebase-chat-sessions-jl"

  - name: SERVING_ENDPOINT
    value: "ka-a05b7a34-endpoint"

  - name: ENABLE_HEADER_AUTH
    value: true

  - name: ENABLE_PASSWORD_AUTH
    value: false

  # - name: DATABASE_INSTANCE
  #   valueFrom: lakebase_postgres
    
  # - name: SERVING_ENDPOINT
  #   valueFrom: ${var.model_endpoint_name}