command: ['chainlit', 'run', 'app.py']


env: 
  - name: CHAINLIT_AUTH_SECRET
    value: "F8*9Z/LVfsoHzEt_/IvaI4s1-.1cd/bQ%Bmd5w5$FcXP$ga=taQR_,YE9Q91xnSG"

  - name: DATABASE_INSTANCE
    value: "<REPLACE_ME_WITH_INSTANCE_NAME>" 

  - name: SERVING_ENDPOINT
    value: "<REPLACE_ME_WITH_ENDPOINT_NAME>"

  - name: ENABLE_HEADER_AUTH
    value: true

  - name: ENABLE_PASSWORD_AUTH
    value: false